# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kodoo < Formula
  desc "Terminal UI for Odoo"
  homepage "https://github.com/chermed/kodoo"
  version "0.2.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chermed/kodoo/releases/download/v0.2.3/kodoo_0.2.3_darwin_amd64.tar.gz"
      sha256 "84e348119273eed8667405efc73d02101be2f6d71f24e4cfe0843da1f21189ea"
    end
    if Hardware::CPU.arm?
      url "https://github.com/chermed/kodoo/releases/download/v0.2.3/kodoo_0.2.3_darwin_arm64.tar.gz"
      sha256 "9212244e6b8f29832aa0046d7e34720a6f0d66d51d62a3f70332721538d8b12b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chermed/kodoo/releases/download/v0.2.3/kodoo_0.2.3_linux_amd64.tar.gz"
      sha256 "9c121fb46b952b8dd17834f0fe26b4eb6d6eba6fc3f972243281db888979fb4f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chermed/kodoo/releases/download/v0.2.3/kodoo_0.2.3_linux_arm64.tar.gz"
      sha256 "5ae6036d5827107ee171e50b6f6b66adff6218bf150c3bceb7f472f8e6707f9b"
    end
  end

  def install
    bin.install "kodoo"
  end

  test do
    system "kodoo version"
  end
end
